version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #   - ./.env:/app/.env
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=catinder
  #     - DATABASE_DSN=mysql://root:password@db/catinder?charset=utf8&parseTime=True&loc=Local
  #   depends_on:
  #     - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=catinder
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
